[workspace]
name = "panel-tiles"
channels = ["pyviz/label/dev", "conda-forge"]
platforms = ["osx-arm64", "osx-64", "linux-64", "win-64"]

[tasks]
postinstall = "pip install --no-build-isolation --no-deps --disable-pip-version-check -e ."
compile = { cmd = "panel compile panel_tiles", env = { PYTHONPATH = "./src:$PYTHONPATH" } }
compile-dev = { cmd = "panel compile panel_tiles --build-dir build --watch", env = { PYTHONPATH = "./src:$PYTHONPATH" } }
pre-commit-install = "pre-commit install"
pre-commit-run = "pre-commit run -a"

[dependencies]
python = ">=3.10"
panel = ">=1.8.3a0"
bokeh = ">=3.8.0"
packaging = "*"
watchfiles = "*"
pip = "*"
nodejs = ">=18"
esbuild = "*"

[feature.py310.dependencies]
python = "3.10.*"
[feature.py311.dependencies]
python = "3.11.*"
[feature.py312.dependencies]
python = "3.12.*"
[feature.py313.dependencies]
python = "3.13.*"
[feature.py313.activation.env]
COVERAGE_CORE = "sysmon"
[feature.py314.dependencies]
python = "3.14.*"
[feature.py314.activation.env]
COVERAGE_CORE = "sysmon"

[environments]
test-310 = ["py310", "compile", "test-core", "test-unit-task"]
test-311 = ["py311", "compile", "test-core", "test-unit-task"]
test-312 = ["py312", "compile", "test-core", "test-unit-task"]
test-313 = ["py313", "compile", "test-core", "test-unit-task"]
test-314 = ["py314", "compile", "test-core", "test-unit-task"]
test-ui = ["py312", "compile", "test-core", "test-ui"]
build = ["py312", "build", "compile"]
compile = ["py312", "compile"]
lint = { features = ["lint"], no-default-feature = true }
docs = ["py311", "doc"]

# =============================================
# ================== TEST =====================
# =============================================

[feature.test-core.dependencies]
pytest = ">=6"
pytest-asyncio = "*"
pytest-cov = "*"
pytest-rerunfailures = "<16"
pytest-xdist = "*"
mypy = "*"
plotly = "*"

[feature.test-unit-task.tasks]
_install = "python -m pip install --no-deps --disable-pip-version-check -e ."
test = { cmd = "pytest", depends-on = ["_install"] }
test-coverage = { cmd = "pytest --cov=panel_tiles --cov-report=xml --cov-report=term-missing", depends-on = ["_install"] }

[feature.test-ui.dependencies]
playwright = "!=1.61.0" # until python-playwright have a release
pytest-playwright = "*"

[feature.test-ui.tasks]
_install = "python -m pip install --no-deps --disable-pip-version-check -e ."
_install-ui = 'playwright install chromium'

[feature.test-ui.tasks.test-ui]
cmd = 'pytest ./tests/ --ui --browser chromium -n logical --dist loadgroup --reruns 3 --reruns-delay 10'
depends-on = [{ task = "_install", environment = 'test-ui' }, "_install-ui"]

# =============================================
# =================== DOCS ====================
# =============================================

[feature.doc.dependencies]
zensical = "<0.0.17"
mkdocstrings = "*"
mkdocstrings-python = "*"

[feature.doc.tasks]
docs-build = { cmd = 'zensical build --clean', depends-on = ['postinstall'] }
docs-serve = { cmd = 'zensical serve', depends-on = ['postinstall'] }
docs-clean = { cmd = 'rm -rf builtdocs', depends-on = ['postinstall'] }

# =============================================
# ================== BUILD ====================
# =============================================

[feature.build.dependencies]
python-build = "*"
twine = "*"
wheel = "*"

[feature.build.tasks]
build-wheel = "python -m build --no-isolation ."
check-wheel = "twine check dist/*"

# =============================================
# ================= COMPILE ===================
# =============================================

[feature.compile.dependencies]
nodejs = ">=18"
esbuild = "*"

# =============================================
# ================== LINT =====================
# =============================================

[feature.lint.dependencies]
pre-commit = "*"

[feature.lint.tasks]
pre-commit-install = "pre-commit install"
pre-commit-run = "pre-commit run -a"
